### PR TITLE
[W5][W15-1] Stanley Mok

### PR DESCRIPTION
**Pull request by stanleymok**
updated userguide to explain the new ping command
added new PingCommand class
added new case to Parser class
updated the tests

### CODE REVIEW

**Comment by rafflesandrison** [comment]
It seems like the Ping Command is used to test the connection status.

Rather than just printing out "ping". I think it would be more meaningful to print out the connection speed (if that is even possible).

**Comment by EugeneYiren** [comment]
Good idea used to test the connection speed of a user. Can also do what Raffles suggested and implement a timer in the function. E.g. elapsed time = end time - start time

**Comment by PhilipPhil** [comment]
very nice. I like what you did with those implementations. Very original.

**Review by leeyh20 — COMMENTED** [review]
Interesting enhancement, but will it be useful for your project? Do try to do enhancements that you are very sure you will be adding to your own project, so that you save time too!

Good job updating documentation. However, do add JUnit tests rather than the command line tests.

**Comment by leeyh20** [comment]
Commit messages should be in present tense. For example, your commit could be: "Update UserGuide with the new Ping command"

It is also advised to split your changes into multiple commits with more details in the commit message.

Do close this PR after reading, thanks!

**Pull request closed without merging**
