### PR TITLE
[W5][W11-2]Wang Zhi Jian

### PR DESCRIPTION
**Pull request by zj-cs2103**
Add `listtag` command to list all persons with a certain tag.

### CODE REVIEW

**Comment by lingyanhao** [comment]
You restructured the list command and added the JUnit tests together in the same commit.
It might be good to separate two changes into separate commits, in case you mess up your work halfway. Also, this makes it easier for a third party to see what is happening to the code base.

**Comment by zj-cs2103** [comment]
Yup I realised that I missed out a commit for adding JUnit tests after restructuring the code. Will take greater care to commit after making changes next time.

**Comment by sinhayash** [comment]
Well done. Some comments:
1. Nice that you have updated tests.
2. It is good that you have incremental changes. You can try to have commits done in a batch for each enhancement. 
3. Wildcard * imports is a coding standard violation, done automatically by Intellij. You need to configure Intellij to stop doing that. See `Parser.java`.

After reading the comments, please close the PR.

**Comment by zj-cs2103** [comment]
Thanks for the review :) Will change my Intellij configuration.

**Pull request closed without merging**
