### PR TITLE
[W5][W15-1]Tan Yiren Eugene

### PR DESCRIPTION
**Pull request by EugeneYiren**
made a more permissible phone, name, email reader

### CODE REVIEW

**Comment by rafflesandrison** [comment]
What if the user input an invalid format ?

I think there should be a mechanism to inform user that their format is not correct.
At the same time, show the format of default valid format + the newly accepted format.

**Comment by PhilipPhil** [comment]
nice bro

**Comment by leeyh20** [comment]
> 
> 
> nice bro

Do try to provide more constructive comments in the future, thanks!

**Comment by leeyh20** [comment]
> 
> 
> nice bro

Do write more for your comment next time! Maybe describe what is nice about this PR?

**Review by leeyh20 — COMMENTED** [review]
Interesting enhancement. It will be better if you add JUnit tests to automate the testing for this enhancement.

**Comment by leeyh20** [comment]
Commit messages should be in present tense. For example, your commit could be: "Allow phone numbers with +"

It is also advised to split your changes into multiple commits with more details in the commit message.

Do close this PR after reading, thanks!

**Pull request closed without merging**
